<a href="https://colab.research.google.com/github/Raziel10/AlgorithmsAndMore/blob/master/ML/kNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import *
import operator # used for sorting 

In [ ]:
def createDataSet ():
  group = array([[1.0,1.1], [1.0,1.0], [0,0], [0,0.1]])
  labels = ['A','A','B','B']
  return group, labels

In [ ]:
group,labels = createDataSet()

In [ ]:
group

array([[1. , 1.1],
       [1. , 1. ],
       [0. , 0. ],
       [0. , 0.1]])

In [ ]:
labels

['A', 'A', 'B', 'B']

For every point in our dataset:
  calculate the distance between inX and the current point 
  sort the distances in increasing order
  take k items with longest distances to inX
  find the majority class among these items
  return the majority class as our prediction for the class of inX

In [ ]:
def classify0( inX, dataSet, labels, k):
  #distance calculation
  dataSetSize = dataSet.shape[0]
  print("dataSetSize:")
  print(str(dataSetSize))
  tileMat = tile(inX, (dataSetSize, 1))
  print("tileMat:")
  print(str(tileMat))
  diffMat = tileMat - dataSet
  print("diffMat:")
  print(str(diffMat))
  sqDiffMat = diffMat**2
  print("sqDiffMat:")
  print(str(sqDiffMat))
  sqDistances = sqDiffMat.sum(axis = 1)
  print("sqDistances:")
  print(str(sqDistances))
  distances = sqDistances**0.5
  print("distances:")
  print(str(distances))
  sortedDistIndicies = distances.argsort()
  print("sortedDistIndicies:")
  print(str(sortedDistIndicies))
  classCount = {}
  #voting with lowest k distances
  for i in range(k):
    voteIlabel = labels[sortedDistIndicies[i]]
    classCount[voteIlabel] = classCount.get(voteIlabel, 0) + 1
  #Sorted dictionary
  sortedClassCount = sorted(classCount.items(), key=operator.itemgetter(1), reverse=True )
  print("sortedClassCount:")
  print(str(sortedClassCount))
  return sortedClassCount[0][0]


In [ ]:
classify0([1,1], group, labels, 3)

dataSetSize:
4
tileMat:
[[1 1]
 [1 1]
 [1 1]
 [1 1]]
diffMat:
[[ 0.  -0.1]
 [ 0.   0. ]
 [ 1.   1. ]
 [ 1.   0.9]]
sqDiffMat:
[[0.   0.01]
 [0.   0.  ]
 [1.   1.  ]
 [1.   0.81]]
sqDistances:
[0.01 0.   2.   1.81]
distances:
[0.1        0.         1.41421356 1.3453624 ]
sortedDistIndicies:
[1 0 3 2]
sortedClassCount:
[('A', 2), ('B', 1)]


'A'

In [ ]:
classify0([0,0], group, labels, 3)

dataSetSize:
4
tileMat:
[[0 0]
 [0 0]
 [0 0]
 [0 0]]
diffMat:
[[-1.  -1.1]
 [-1.  -1. ]
 [ 0.   0. ]
 [ 0.  -0.1]]
sqDiffMat:
[[1.   1.21]
 [1.   1.  ]
 [0.   0.  ]
 [0.   0.01]]
sqDistances:
[2.21 2.   0.   0.01]
distances:
[1.48660687 1.41421356 0.         0.1       ]
sortedDistIndicies:
[2 3 1 0]
sortedClassCount:
[('B', 2), ('A', 1)]


'B'