# Understanding Scalar, Vector, and Matrix Operations
by Raziel Lopez Escamilla

## Creating a matrix


import numpy libray, useful for array and matrix operations

In [1]:
import numpy as np 

myMatrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(myMatrix)
print(myMatrix[0,0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1


Example of how to crete an array and access an element

In [2]:
myMatrix = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(myMatrix)
print(myMatrix[0, 1, 1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4


Sometimes it will be useful to create an array full of ones, in the next example we fill a matrix with ones where the data types is an integer of 32 bits

In [3]:
myMatrix = np.ones([4,4], dtype=np.int32)
print(myMatrix)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


It is also posible to create an array with an specific datatype, in the next example we create an array with boolean elements

In [4]:
myMatrix = np.ones([4,4,4], dtype=np.bool)
print(myMatrix)

[[[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


Apart from creating arrays it is also posible to create matrices, this are useful at the moment of doing matrix operations

In [5]:
myMatrix = np.mat([[1,2,3], [4,5,6], [7,8,9]])
print(myMatrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Performing matrix multiplication

arrays can be multiplied, this operations make an element by element operation

In [6]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])

print(a*b)

[[ 1  4  9]
 [16 25 36]]


If we need to perform a dot product with an array, we need to use the dot method as following

In [7]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[3,4,5],[5,6,7]])

print(a.dot(b))

[[22 28 34]
 [49 64 79]]


in case we have a matrix (np.mat) we just need to use the * operator to make a dot product between two matrices

In [8]:
a = np.mat([[1,2,3],[4,5,6]])
b = np.mat([[1,2,3],[3,4,5],[5,6,7]])

print(a*b)

[[22 28 34]
 [49 64 79]]


## Executing advanced matrix operations

Arrays can be reshaped to a different dimesion using existing values inside array by using the reshape method, it will be possible as long as the amount of elements inside the array are enough to fill all elements of the new array

In [11]:
changeIt = np.array([1,2,3,4,5,6,7,8])

print(changeIt)

print(changeIt.reshape(2,4))

print(changeIt.reshape(2,2,2))

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


example of how to obtain the transpose of an array 

In [12]:
changeIt = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(np.transpose(changeIt))

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


there is also a method for identity matrices

In [13]:
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


example of how to obtain the inverse of a matrix and compare with another one by suned allclase method

In [16]:
a = np.array([[1,2], [3,4]])
b = np.linalg.inv(a)

print(np.allclose(np.dot(a,b), np.identity(2)))

True


## Extending analysis to tensors

In [18]:
inputs = np.array([5, 10, 15])
weights = np.array([[.5,.2,-1], [.3,.4,.1], [-.2,.1,.3]])

result = np.dot(inputs, weights)
print(result)

[2.5 6.5 0.5]


## Using vectorization effectively

In [25]:
def doAdd(a, b):
    return a + b

vectAdd = np.vectorize(doAdd)

print(vectAdd([1, 2, 3, 4], [1, 2, 3, 4]))

[2 4 6 8]
