
# Redes Neuronales Convolucionales 
por Raziel López Escamilla.

#Introducción.

Las redes neuronales convolucionales consisten en múltiples capas de filtros convolucionales de una o más dimensiones. Después de cada capa, por lo general se añade una función para realizar un mapeo causal no-lineal.

Este tipo de red es una variación de un perceptron multicapa, sin embargo, debido a que su aplicación es realizada en matrices bidimensionales, son muy efectivas para tareas de visión artificial, como en la clasificación y segmentación de imágenes, entre otras aplicaciones

A continuacion se mostrará un ejempo de una red CNN utilizando TensorFlow

MNIST_V_9

Importar libreriras

In [ ]:
import tensorflow as tf        #Tensorflow
import numpy as np             #numpy 
from tensorflow import keras   # Keras 

Librería Mnist y tratamos ls datos 
(28x28x1)---blanco/negro     (28x28x3) RGB----- a color 

In [ ]:
#  Parámetros 
EPOCHS = 3          
BATCH_SIZE = 220     #Batch size
VERBOSE = 2         
NB_CLASSES = 10      #digits from 0 to 9
N_HIDDEN = 2048      
VALIDATION_SPLIT=0.999 # how much TRAIN is reserved for VALIDATION
DROPOUT = 0.5          # Droput para overfiting 

Cargar el MNSIST para el dataset

In [ ]:
# verify
# the split between train and test is 60,000, and 10,000 respectly 
# one-hot is automatically applied
mnist = keras.datasets.mnist                               #dataset de mnist
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()   #Cargamos el dataset 

Se agrega formato a los arreglos de prueba y de entrenamiento.

In [ ]:
#X_train is 60000 rows of 28x28 values --> reshaped in 60000 x 784
RESHAPED = 784
#
X_train = X_train.reshape(60000, RESHAPED)     
X_test = X_test.reshape(10000, RESHAPED)       
X_train = X_train.astype('float32')             
X_test = X_test.astype('float32')            

Se normalizan los arreglos.

In [ ]:
#normalize in [0,1]
X_train, X_test = X_train / 255.0, X_test / 255.0      
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

60000 train samples
10000 test samples


Se representa de forma vectorial.

In [ ]:
#one-hot
Y_train = tf.keras.utils.to_categorical(Y_train, NB_CLASSES)       
Y_test = tf.keras.utils.to_categorical(Y_test, NB_CLASSES)

Creación del modelo con 3 capas con un modelo secuancial



In [ ]:
#build the model
model = tf.keras.models.Sequential()                  

model.add(keras.layers.Dense(N_HIDDEN,                 
   		input_shape=(RESHAPED,),
   		name='dense_layer', activation='relu'))        
model.add(keras.layers.Dropout(DROPOUT))
 
model.add(keras.layers.Dense(N_HIDDEN,                
   		name='dense_layer_2', activation='relu'))
model.add(keras.layers.Dropout(DROPOUT))               

model.add(keras.layers.Dense(NB_CLASSES,              
   		name='dense_layer_3', activation='softmax'))

Se muestra un resumen del modelo

In [ ]:
# summary of the model
model.summary()                       

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_layer (Dense)          (None, 2048)              1607680   
_________________________________________________________________
dropout (Dropout)            (None, 2048)              0         
_________________________________________________________________
dense_layer_2 (Dense)        (None, 2048)              4196352   
_________________________________________________________________
dropout_1 (Dropout)          (None, 2048)              0         
_________________________________________________________________
dense_layer_3 (Dense)        (None, 10)                20490     
Total params: 5,824,522
Trainable params: 5,824,522
Non-trainable params: 0
_________________________________________________________________


compilamos el modelo, utilizando optimizador adam, funcion de perdida y calculando la precisión del modelo. 

In [ ]:
# compiling the model
model.compile(optimizer='Adam',                    
              loss='categorical_crossentropy',    
              metrics=['accuracy'])   

entrenamiento del modelo

In [ ]:
#training the moodel                                            #entrenamos el modelo 
model.fit(X_train, Y_train,
		batch_size=BATCH_SIZE, epochs=EPOCHS,                   
		verbose=VERBOSE, validation_split=VALIDATION_SPLIT)


Epoch 1/3
1/1 - 4s - loss: 2.2656 - accuracy: 0.1833 - val_loss: 2.0427 - val_accuracy: 0.3163
Epoch 2/3
1/1 - 3s - loss: 1.7614 - accuracy: 0.5167 - val_loss: 1.7424 - val_accuracy: 0.4684
Epoch 3/3
1/1 - 3s - loss: 1.2397 - accuracy: 0.7000 - val_loss: 1.4350 - val_accuracy: 0.5910


Evaluamos el modelo y se calcula presición.

In [ ]:
test_loss, test_acc = model.evaluate(X_test, Y_test)
print('Test accuracy:', test_acc)

313/313 [==============================] - 2s 7ms/step - loss: 1.4329 - accuracy: 0.5857
Test accuracy: 0.5856999754905701


Hacemos una predicción 

In [ ]:
predictions = model.predict(X_test)
print(predictions)

[[0.06224658 0.05407007 0.10215508 ... 0.1660852  0.09695984 0.26234508]
 [0.08884829 0.12121257 0.11924042 ... 0.03204749 0.06090078 0.02887413]
 [0.04789393 0.37023085 0.05925105 ... 0.05711152 0.08973812 0.07316941]
 ...
 [0.01285272 0.04867186 0.04534056 ... 0.0558794  0.10805231 0.4761033 ]
 [0.07834467 0.20341018 0.07541793 ... 0.05883632 0.15121335 0.13986273]
 [0.21576425 0.05685443 0.06157725 ... 0.02991032 0.02457118 0.01348476]]


##Conclusion.

Dada a la naturaleza de las convoluciones dentro de las redes neuronales convolucionales, estas son aptas para poder aprender a clasificar todo tipo de datos donde estos estén distribuidos de una forma continua a lo largo del mapa de entrada, y a su vez sean estadísticamente similares en cualquier lugar del mapa de entrada. Por esta razón, son especialmente eficaces para clasificar imágenes, por ejemplo para el auto-etiquetado de imágenes.

Sin embargo, las redes neuronales convolucionales también pueden ser aplicadas para la clasificación de series de tiempo o señales de audio utilizando convoluciones en una dimension, así como para la clasificación de datos volumétricos usando convoluciones en 3D